definitions:
  entity.User:
    properties:
      _id:
        type: string
      email:
        type: string
      name:
        type: string
      role:
        type: integer
    type: object
  model.UserRequest:
    properties:
      email:
        maxLength: 255
        minLength: 1
        type: string
      name:
        maxLength: 255
        minLength: 1
        type: string
      role:
        type: integer
    required:
    - email
    - name
    - role
    type: object
info:
  contact: {}
paths:
  /api/v1/user:
    get:
      description: Get all users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.User'
            type: array
      summary: Get all users
      tags:
      - Users
    post:
      description: Add new users
      parameters:
      - description: User payload
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/model.UserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.User'
      summary: Add new users
      tags:
      - Users
swagger: "2.0"
